2022-0510-01)
FUNCTION
 (사용예)회원아이디를 받으면 해당 이름을 리턴하는 함수 만들기
 SET SERVEROUTPUT ON
 /
    CREATE OR REPLACE FUNCTION FN_GETNAME
    (P_MEM_ID IN VARCHAR2)
        RETURN VARCHAR2
    IS
        V_NAME VARCHAR2(30);
    BEGIN
        SELECT MEM_NAME INTO V_NAME
          FROM MEMBER
         WHERE MEM_ID = P_MEM_ID;
         
        RETURN V_NAME;
    END;
/
SELECT FN_GETNAME('b001') FROM DUAL;
 (사용예)년도 및 상품코드를 입력 받으면 해당년도의 평균 판매횟수를 반환하는 함수
/
    CREATE OR REPLACE FUNCTION FN_PRODAVGQTY
    (P_YEAR IN NUMBER DEFAULT(EXTRACT(YEAR FROM SYSDATE)), P_CPROD IN VARCHAR2)
        RETURN NUMBER
    IS
        V_QTY NUMBER;
    BEGIN
        SELECT NVL(ROUND(AVG(CART_QTY),2),0) INTO V_QTY
          FROM CART
         WHERE CART_PROD = P_CPROD
           AND CART_NO LIKE P_YEAR||'%';
           
        RETURN V_QTY;
    END;
/
VAR QTY NUMBER
EXEC : QTY := FN_PRODAVGQTY(2020, 'P101000001')
PRINT QTY;
--함수 사용법--
SELECT PROD_ID, PROD_NAME,
       FN_PRODAVGQTY(2020, PROD_ID) AS AVG_QTY_2020,
       FN_PRODAVGQTY(2021, PROD_ID) AS AVG_QTY_2021
  FROM PROD;
 (사용예)상품코드, 상품명, 대분류코드, 대분류명을 출력하자
        함수를 생성하여 대분류명을 처리해보자, 함수명: FN_PRODNM
/        
    CREATE OR REPLACE FUNCTION FN_PRODNM(P_PROD_LGU IN VARCHAR2)
    RETURN VARCHAR2
    IS
        V_NM VARCHAR2(30);
    BEGIN
        SELECT LPROD_NM INTO V_NM
          FROM LPROD
         WHERE LPROD_GU = P_PROD_LGU;
        
        RETURN V_NM;
    END;
/
    SELECT PROD_ID, PROD_NAME, PROD_LGU,
           FN_PRODNM(PROD_LGU) AS PROD_NM
      FROM PROD;
/