2022-0506-02)
STORED PROCEDURE
 - 오라클 서버의 캐시공간에 미리 저장된 프로시져
 - 업데이트 셋 웨어
 /
    SELECT PROD_ID, PROD_TOTALSTOCK
      FROM PROD
     WHERE PROD_ID = 'P101000001';
/
    /
    CREATE OR REPLACE PROCEDURE USP_PROD_TOTALSTOCK_UPDATE IS 
    BEGIN
      UPDATE PROD
         SET PROD_TOTALSTOCK = PROD_TOTALSTOCK + 10
       WHERE PROD_ID = 'P101000001';
       DBMS_OUTPUT.PUT_LINE('업데이트 성공!');
      COMMIT;
    END; --실행이 아니라 컴파일 된다.
    /
    --STORED PROCEDURE 실행--
    EXECUTE USP_PROD_TOTALSTOCK_UPDATE;
    EXEC USP_PROD_TOTALSTOCK_UPDATE;